### ISSUE TITLE
Update arm-none-eabi-gcc for SAMD boards

### ISSUE THREAD

**Issue by stonehippo** [sparkfun/Arduino_Boards#115]
The 1.8.11 version bundles a fairly old version of the arm-none-eabi-gcc (excerpt below).

```
            {
              "packager": "arduino",
              "name": "arm-none-eabi-gcc",
              "version": "4.8.3-2014q1"
            },
```

This is the version that was packaged with older versions of the Arduino SAMD board support. However, newer versions have updated this toolchain:

```
            {
              "packager": "arduino",
              "name": "arm-none-eabi-gcc",
              "version": "7-2017q4"
            },
```

It would be great to have the Sparkfun Arduino BSP updated to more recent versions. Among other things, this would fix install issues on some platforms, including Raspberry PI/aarch64, where there is no package available for the older 2014 gcc.

**Comment by edspark** [comment]
Thanks for bringing this to our attention. I'll get this updated sometime today.

**Comment by edspark** [comment]
I updated the version used in the package json in the latest release 1.8.12, and I think the IDE is smart enough to use it since it's bundled with Arduino's SAMD packages and our release depends on theirs.  if I've missed something, please don't hesitate to let me know!
