### ISSUE TITLE
Cannot run program "/home/edwin/sketchbook/hardware/esp8266/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-g++" (in directory "."): error=2, No such file or directory

### ISSUE THREAD

**Issue by consolacion** [sparkfun/Arduino_Boards#14]
I get the error Cannot run program "/home/user/sketchbook/hardware/esp8266/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-g++" (in directory "."): error=2, No such file or directory
I saw someone had that here before but apparently 'solved'it by removing a space in the "preference dialog"  but there is no space there. Also, I seem to remember it has worked before.
What is causing this and what can I do. I am on 32 bit ubuntu

**Comment by bboyho** [comment]
Hi,

I'm sorry for the delay in reply. I was going through some of the issues that have been open. I'm not sure what is causing this. I would need more information to determine what happened. It appears that you might have been using one of the ESP8266 board variants.

There are two possible reasons for this compile error based on my experience with the ESP8266. It could be the Arduino IDE version that you are using  on your computer or a conflicting ESP8266 board definition. If you have not already determined the cause of the compile error, try the following:

* reinstalling the [Arduino IDE](https://www.arduino.cc/en/Main/Software)
* using a [different version](https://www.arduino.cc/en/Main/OldSoftwareReleases#previous)
* or [reinstalling the board add-on files](https://learn.sparkfun.com/tutorials/esp8266-thing-development-board-hookup-guide/setting-up-arduino)

It looks like there was a recent update in the ESP8266 tutorials that uses the ESP8266 as opposed to the one that was listed in this repo.
