### ISSUE TITLE
sparkfunboards v1.1.4 borken

### ISSUE THREAD

**Issue by stejsoftware** [sparkfun/Arduino_Boards#15]
I updated sparkfunboards from v1.1.3 to v1.1.4 and now get this.

```
Arduino:` 1.6.8 (Windows 7), Board: "SparkFun Pro Micro, ATmega32U4 (3.3V, 8 MHz)"

Board promicro (platform avr, package SparkFun) is unknown

Error compiling for board SparkFun Pro Micro.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

**Comment by BrentWilkins** [comment]
Please see issue #12.

**Comment by stejsoftware** [comment]
Yea I figured out its actually a problem with the Arduino IDE. Once I found where the files were being installed i removed them all and tried again. It works now. You can close this ticket. Thanks!
