### ISSUE TITLE
Bundles outdated avrdude.conf

### ISSUE THREAD

**Issue by rpavlik** [sparkfun/Arduino_Boards#21]
This appears to bundle an outdated avrdude.conf file that doesn't contain information on the ATMEL-ICE device used as an ISP. I can burn bootloaders on non-SparkFun devices using it, but trying to flash a Pro Micro 5V/16MHz bootloader uses this command line and has this output (using Arduino 1.6.13 with latest Arduino AVR boards pack)

```
C:\Users\Ryan\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino9/bin/avrdude -CC:\Users\Ryan\AppData\Local\Arduino15\packages\SparkFun\hardware\avr\1.1.5/avrdude.conf -v -patmega32u4 -catmelice_isp -Pusb -e -Ulock:w:0x3F:m -Uefuse:w:0xCB:m -Uhfuse:w:0xD8:m -Ulfuse:w:0xFF:m 

avrdude: Version 6.3, compiled on Jan 17 2017 at 12:00:53
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "C:\Users\Ryan\AppData\Local\Arduino15\packages\SparkFun\hardware\avr\1.1.5/avrdude.conf"


avrdude: Can't find programmer id "atmelice_isp"

```

**Comment by jimblom** [comment]
I've just pushed an update to the AVR core with a much more recent version of avrdude.conf.

@rpavlik Thanks for the heads up! Sorry for letting this languish for so long.
