### ISSUE TITLE
where are the promicro drivers?

### ISSUE THREAD

**Issue by mholgatem** [sparkfun/Arduino_Boards#26]
I had to dig around in the forums to find a pro micro driver, shouldn't they be inside the Arduino_Boards/sparkfun/avr/driver/ folder?

**Comment by ToniCorinne** [comment]
The Pro Micros use the Caterina bootloader. You can find the 8MHz and 16MHz version here: https://github.com/sparkfun/Arduino_Boards/tree/master/sparkfun/avr/bootloaders/caterina.

The signed drivers for the AtMega32U4s lives here: https://github.com/sparkfun/Arduino_Boards/tree/master/sparkfun/avr/signed_driver

**Comment by mholgatem** [comment]
great! thanks!
