### ISSUE TITLE
Use the "Processor" drop-down to consolidate the two Pro Micro board files

### ISSUE THREAD

**Issue by bhuang10000** [sparkfun/Arduino_Boards#3]
Can we consolidate the two Pro Micro boards in the drop-down to a single entry and use the "Processor" drop-down to select which Voltage \ Speed you're running at? The Pro / Pro Mini uses this feature.

**Comment by BrentWilkins** [comment]
I made the change for the Pro Micro boards and the Mega Pro boards.
