### ISSUE TITLE
Add Mac paths to the install notes

### ISSUE THREAD

**Issue by JamesHagerman** [sparkfun/Arduino_Boards#4]
Please?

**Comment by BrentWilkins** [comment]
If you use on of the more recent 1.6.x versions, just add https://github.com/sparkfun/Arduino_Boards/blob/master/IDE_Board_Manager/package_sparkfun_index.json to the "Additional Boards Manager URLs:' list and our stuff will appear in the 'Boards Manager...' in the 'Tools' menu.

**Comment by ToniCorinne** [comment]
Closing this issue out. Please open a new one if you were looking for different instructions.
