### ISSUE TITLE
archiveFileName 1.1.12 incorrect

### ISSUE THREAD

**Issue by jpliew** [sparkfun/Arduino_Boards#42]
https://github.com/sparkfun/Arduino_Boards/blob/1e869335945ec8f48489a73ddc7472f9ffbf72cf/IDE_Board_Manager/package_sparkfun_index.json#L358

should be

          "archiveFileName": "sparkfunboards.1.1.12.tar.bz2"

Thanks
JP

**Comment by jimblom** [comment]
Hi JP!

Issue should be addressed in commit ea84205. Thanks for your help!
