### ISSUE TITLE
3 PIDs

### ISSUE THREAD

**Issue by BrentWilkins** [sparkfun/Arduino_Boards#6]
Why are there 3 PIDs for the MaKey MaKey?

**Comment by jimblom** [comment]
Looks like an error in [IDE_Board_Manager/1.0.1/boards.txt](https://github.com/sparkfun/Arduino_Boards/blob/master/IDE_Board_Manager/1.0.1/boards.txt#L65). `build.pid` should be 0x2B75 (0x9206 is a Pro Micro 5V).

**Comment by jimblom** [comment]
Looks like the Fio v3's got a similar issue: [https://github.com/sparkfun/Arduino_Boards/blob/master/IDE_Board_Manager/1.0.1/boards.txt#L154](https://github.com/sparkfun/Arduino_Boards/blob/master/IDE_Board_Manager/1.0.1/boards.txt#L154).

**Comment by jimblom** [comment]
The updated AVR package 1.0.2 includes this fix. Also updated sparkfun/avr/boards.txt.
