### ISSUE TITLE
bossac fails on Windows 10 Arduino 1.8.10 and Sparkfun samd 1.7.2 boards

### ISSUE THREAD

**Issue by LuisCRSousa** [sparkfun/Arduino_Boards#60]
`java.io.IOException: Cannot run program "{runtime.tools.bossac-1.7.0-arduino3.path}/bossac.exe": CreateProcess error=2`

New arduino and sparkfun SAMD boards

**Comment by LuisCRSousa** [comment]
It works if I choose the  Arduino/Genuino Zero (Native USB Port) board

**Comment by edspark** [comment]
I can't confirm this behavior. I'm running on Arduino 1.8.10 and using the latest 1.7.2 package.

**Comment by edspark** [comment]
Please re-open this issue if you're still having issues.
