### ISSUE TITLE
Variant.cpp file for RedBoard Turbo needs additional PinDescription entries in g_APinDescription array

### ISSUE THREAD

**Issue by sdward-github** [sparkfun/Arduino_Boards#69]
Variant.cpp file for RedBoard Turbo needs additional PinDescription entries in g_APinDescription array for FLASH_MISO (PB03) .  There does not currently appear to be an entry for PORTB pin 3 (PB03) in the g_APinDescription array. I believe the entry should be as follows:

{ PORTB, 3, PIO_SERCOM_ALT, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }

FLASH_MOSI (PB22) and FLASH_SCK (PB23) already have entries in g_APinDescription.

**Comment by edspark** [comment]
Yes quite odd that it didn't make it into the pin description list. I have simply [added it to the end](https://github.com/sparkfun/Arduino_Boards/commit/c826514c3662aee5d3db498776ba3b7a64db303e) and you'll just have to reassign the SERCOM port in your sketch to use SPI with the flash.
