### ISSUE TITLE
Issue #69 fix breaks samd/variants/SparkFun_RedBoard_Turbo/variant.cpp

### ISSUE THREAD

**Issue by DavidArmstrong** [sparkfun/Arduino_Boards#72]
Lines 199-203 in samd/variants/SparkFun_RedBoard_Turbo/variant.cpp now reads as follows:

  // 44 - RGB LED
  { PORTA,  30, PIO_DIGITAL, (PIN_ATTR_DIGITAL), No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }	// 44: RGB LED

  //45
  { PORTB, 3, PIO_SERCOM_ALT, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // 31/RX: SERCOM5/PAD[3]

The pin definition for Pin 44 needs to end in a comma, after the closing right brace, so that the new Pin 45 definition that follows it is valid.  As it is now, compiling a sketch on the Redboard Turbo generates a compiler error here.

**Comment by edspark** [comment]
You are right, I've fixed it and verified the fix. Sorry about the completely unnecessary headache.
