### ISSUE TITLE
Install error when loading AVR board using the ESP8266 package

### ISSUE THREAD

**Issue by stonehippo** [sparkfun/Arduino_Boards#8]
When using the ESP8266 board manager URL, attempting to install the Sparkfun AVR board definitions results in a failure due to a CRC error with the `sparkfunboards.tar.bz2` file. The issue arises from the current version of the AVR package having been upgraded to 1.0.1 while the ESP8266 package still has the SHA information for the 1.0.0 version.

I have created a pull request, issue #7, which should resolve this temporarily by updating `package_sparkfun_index.json` in the ESP8266 branch to include the AVR board 1.0.1 package information.

**Comment by jimblom** [comment]
Thanks for all your help!

I've merged the ESP8266 branch contents into master, so the AVR and ESP8266 definitions are all included in the same "package_sparkfun_index.json" file. That should resolve this and any similar issues that may come up in the future.

ESP8266 development will continue in the master branch, and the ESP8266 branch will go away once we get documentation all caught up.
