### ISSUE TITLE
Tried adding these to Arduino 1.6.5, throws erros

### ISSUE THREAD

**Issue by JoelEB** [sparkfun/Arduino_Boards#9]
![screen shot 2015-10-21 at 12 23 15 pm](https://cloud.githubusercontent.com/assets/1051208/10646112/a11fd864-77ee-11e5-8d12-03670a4ca956.png)

**Comment by BrentWilkins** [comment]
Worked for me.  Will you please give me more information on how to recreate the error?
(Note: https://raw.githubusercontent.com/sparkfun/Arduino_Boards/master/IDE_Board_Manager/package_sparkfun_index.json)

**Comment by JoelEB** [comment]
Brent and I figured out we needed to add the URL to the Arduino Preferences list of URLs first.
